export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_ANIME_FRIENDS_PENDING = 'REQUEST_ANIME_FRIENDS_PENDING';
export const REQUEST_ANIME_FRIENDS_SUCCESS = 'REQUEST_ANIME_FRIENDS_SUCCESS';
export const REQUEST_ANIME_FRIENDS_FAILED = 'REQUEST_ANIME_FRIENDS_FAILED';